sudo: false
cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""

jobs:
  include:
    - php: 7.4
      env:
        - PREFER_LOWEST=""
        - CODE_COVERAGE="--coverage-clover build/logs/clover.xml"

before_install:
  - if [[ $TRAVIS_PHP_VERSION > 7.4 ]] ; then sed -i '/friendsofphp\/php-cs-fixer/d' composer.json; fi;
  - composer self-update

install:
  - travis_retry composer update --no-interaction $PREFER_LOWEST --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit $CODE_COVERAGE
  - if [[ $TRAVIS_PHP_VERSION < 7.4 ]] ; then composer run-script lint; fi;

after_script:
  - if [[ $CODE_COVERAGE != '' ]]; then php vendor/bin/php-coveralls -v; fi;
