sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
  #- ./vendor/bin/phpunit -c phpunit.xml.jsonmapper
  - if [[ $TRAVIS_PHP_VERSION < 7.4 ]] ; then composer run-script fix-cs; fi;

  after_script:
    - php vendor/bin/coveralls -v

  matrix:
    allow_failures:
      - php: 7.4snapshot
      - php: nightly
