sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_install:
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION != 7.3 or $PREFER_LOWEST  != "" ]] ; then phpenv config-rm xdebug.ini; fi;

install:
  - travis_retry composer update --no-interaction $PREFER_LOWEST --prefer-source

script:
  - ./vendor/bin/phpunit
  - if [[ $TRAVIS_PHP_VERSION < 7.4 ]] ; then composer run-script fix-cs; fi;

after_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.3 and $PREFER_LOWEST  = "" ]] ; then php vendor/bin/php-coveralls -v; fi;

matrix:
  allow_failures:
    - php: nightly
